-- Revive the recovered Glitch Airdrop Farm operational database.
-- Postgres is authoritative; no historical mirror data or wallet secrets are imported.

create extension if not exists pgcrypto with schema extensions;
create extension if not exists pg_trgm with schema extensions;

create table public.identity (
  id uuid primary key default extensions.gen_random_uuid(),
  label text not null,
  camofox_user_id text not null unique,
  proxy_url text not null,
  proxy_country text not null,
  locale text not null,
  timezone text not null,
  user_agent text not null,
  persona jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  retired_at timestamptz,
  constraint identity_label_not_blank check (btrim(label) <> ''),
  constraint identity_proxy_country_not_blank check (btrim(proxy_country) <> ''),
  constraint identity_persona_is_object check (jsonb_typeof(persona) = 'object'),
  constraint identity_retired_after_created check (
    retired_at is null or retired_at >= created_at
  )
);

create index identity_active on public.identity (retired_at)
  where retired_at is null;

create table public.wallet (
  id uuid primary key default extensions.gen_random_uuid(),
  identity_id uuid not null unique
    references public.identity(id) on delete restrict,
  chain_family text not null,
  address text not null,
  privkey_enc bytea not null,
  derivation text,
  funded_at timestamptz,
  status text not null default 'fresh',
  created_at timestamptz not null default now(),
  constraint wallet_chain_family_check check (chain_family in ('evm', 'svm')),
  constraint wallet_status_check check (
    status in ('fresh', 'warming', 'active', 'paused', 'burned')
  ),
  constraint wallet_address_not_blank check (btrim(address) <> ''),
  constraint wallet_privkey_enc_not_empty check (octet_length(privkey_enc) > 0),
  constraint wallet_chain_address_key unique (chain_family, address),
  constraint wallet_funded_after_created check (
    funded_at is null or funded_at >= created_at
  )
);

create index wallet_status on public.wallet (status);

create table public.protocol (
  id text primary key,
  display_name text not null,
  chain text not null,
  status text not null default 'active',
  weight integer not null default 10,
  notes text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint protocol_id_not_blank check (btrim(id) <> ''),
  constraint protocol_display_name_not_blank check (btrim(display_name) <> ''),
  constraint protocol_chain_not_blank check (btrim(chain) <> ''),
  constraint protocol_status_check check (
    status in ('active', 'paused', 'snapshotted', 'dead')
  ),
  constraint protocol_weight_check check (weight between 1 and 100),
  constraint protocol_metadata_is_object check (jsonb_typeof(metadata) = 'object')
);

create table public.enrollment (
  wallet_id uuid not null
    references public.wallet(id) on delete cascade,
  protocol_id text not null
    references public.protocol(id) on delete cascade,
  started_at timestamptz not null default now(),
  last_action_at timestamptz,
  total_actions integer not null default 0,
  total_gas_usd numeric(10,4) not null default 0,
  points_cached jsonb,
  points_at timestamptz,
  status text not null default 'active',
  primary key (wallet_id, protocol_id),
  constraint enrollment_total_actions_check check (total_actions >= 0),
  constraint enrollment_total_gas_usd_check check (total_gas_usd >= 0),
  constraint enrollment_status_check check (
    status in ('active', 'done', 'abandoned')
  ),
  constraint enrollment_last_action_after_started check (
    last_action_at is null or last_action_at >= started_at
  )
);

create index enrollment_protocol on public.enrollment (protocol_id);

create table public.action (
  id bigint generated by default as identity primary key,
  wallet_id uuid not null references public.wallet(id),
  protocol_id text not null references public.protocol(id),
  action_type text not null,
  tx_hash text,
  amount_usd numeric(12,4),
  gas_usd numeric(10,4),
  metadata jsonb not null default '{}'::jsonb,
  succeeded boolean,
  error text,
  executed_at timestamptz not null default now(),
  constraint action_type_not_blank check (btrim(action_type) <> ''),
  constraint action_amount_usd_check check (amount_usd is null or amount_usd >= 0),
  constraint action_gas_usd_check check (gas_usd is null or gas_usd >= 0),
  constraint action_metadata_is_object check (jsonb_typeof(metadata) = 'object')
);

create index action_wallet_time
  on public.action (wallet_id, executed_at desc);
create index action_protocol_time
  on public.action (protocol_id, executed_at desc);

create table public.job (
  id bigint generated by default as identity primary key,
  wallet_id uuid not null references public.wallet(id),
  protocol_id text not null references public.protocol(id),
  playbook text not null,
  params jsonb not null default '{}'::jsonb,
  scheduled_for timestamptz not null,
  claimed_by text,
  claimed_at timestamptz,
  finished_at timestamptz,
  succeeded boolean,
  result jsonb,
  attempts integer not null default 0,
  created_at timestamptz not null default now(),
  constraint job_playbook_not_blank check (btrim(playbook) <> ''),
  constraint job_params_is_object check (jsonb_typeof(params) = 'object'),
  constraint job_attempts_check check (attempts >= 0),
  constraint job_claim_pair_check check (
    (claimed_by is null and claimed_at is null)
    or (claimed_by is not null and claimed_at is not null)
  ),
  constraint job_finish_state_check check (
    (finished_at is null and succeeded is null)
    or finished_at is not null
  ),
  constraint job_claimed_after_created check (
    claimed_at is null or claimed_at >= created_at
  ),
  constraint job_finished_after_created check (
    finished_at is null or finished_at >= created_at
  )
);

-- Workers claim one due row with FOR UPDATE ... SKIP LOCKED. This partial
-- index preserves the recovered queue's ready-job lookup semantics.
create index job_ready on public.job (scheduled_for)
  where finished_at is null and claimed_by is null;
create index job_wallet on public.job (wallet_id);
create index job_protocol on public.job (protocol_id);

create table public.points_snapshot (
  id bigint generated by default as identity primary key,
  wallet_id uuid not null references public.wallet(id),
  protocol_id text not null references public.protocol(id),
  points numeric(20,6) not null,
  rank integer,
  raw jsonb,
  taken_at timestamptz not null default now(),
  constraint points_snapshot_points_check check (points >= 0),
  constraint points_snapshot_rank_check check (rank is null or rank > 0)
);

create index ps_lookup
  on public.points_snapshot (wallet_id, protocol_id, taken_at desc);
create index points_snapshot_protocol on public.points_snapshot (protocol_id);

create table public.funding (
  id bigint generated by default as identity primary key,
  wallet_id uuid references public.wallet(id),
  direction text not null,
  source text,
  asset text not null,
  amount numeric(28,12) not null,
  amount_usd numeric(12,4),
  tx_hash text,
  chain text,
  at timestamptz not null default now(),
  notes text,
  constraint funding_direction_check check (
    direction in ('in', 'out', 'internal')
  ),
  constraint funding_asset_not_blank check (btrim(asset) <> ''),
  constraint funding_amount_check check (amount > 0),
  constraint funding_amount_usd_check check (
    amount_usd is null or amount_usd >= 0
  )
);

create index funding_wallet on public.funding (wallet_id);

-- These are server-side operational tables. RLS is defense in depth; no
-- anon/authenticated policies are intentionally created.
alter table public.identity enable row level security;
alter table public.wallet enable row level security;
alter table public.protocol enable row level security;
alter table public.enrollment enable row level security;
alter table public.action enable row level security;
alter table public.job enable row level security;
alter table public.points_snapshot enable row level security;
alter table public.funding enable row level security;

revoke all privileges on table
  public.identity,
  public.wallet,
  public.protocol,
  public.enrollment,
  public.action,
  public.job,
  public.points_snapshot,
  public.funding
from anon, authenticated, service_role;

revoke all privileges on all sequences in schema public
from anon, authenticated, service_role;

-- Make future objects created by the migration owner opt-in to Data API access.
alter default privileges for role postgres in schema public
  revoke all on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke all on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public, anon, authenticated, service_role;

insert into public.protocol
  (id, display_name, chain, status, weight, notes)
values
  ('monad-tn', 'Monad Testnet', 'monad-testnet', 'active', 45,
   'Testnet → mainnet TGE 2026. Highest-EV testnet farm.'),
  ('megaeth-tn', 'MegaETH Testnet', 'megaeth-testnet', 'active', 40,
   'Active campaign. Real-time L2 thesis, TGE 2026.'),
  ('berachain-tn', 'Berachain Bartio', 'berachain-bartio', 'active', 35,
   'Bartio testnet feeds mainnet drop.'),
  ('linea-tn', 'Linea Sepolia', 'linea-sepolia', 'active', 10,
   'EVM practice surface; mirror of mainnet flow.'),
  ('scroll-tn', 'Scroll Sepolia', 'scroll-sepolia', 'active', 10,
   'EVM practice surface.'),
  ('linea', 'Linea LXP', 'linea-mainnet', 'paused', 35,
   'L2 from ConsenSys. LXP → TGE 2026.'),
  ('scroll', 'Scroll Sessions', 'scroll-mainnet', 'paused', 25,
   'Scroll Marks program.'),
  ('berachain', 'Berachain BGT', 'berachain-mainnet', 'paused', 30,
   'Post-mainnet BGT/HONEY ecosystem.'),
  ('hyperliquid', 'Hyperliquid Season 2', 'hyperliquid-l1', 'paused', 40,
   'S1 paid $50k–$500k/wallet.'),
  ('jupiter', 'Jupiter LFG', 'solana-mainnet', 'paused', 25,
   'Solana DEX, recurring rewards.'),
  ('kamino', 'Kamino kPoints', 'solana-mainnet', 'paused', 20,
   'SOL lending.'),
  ('eigenlayer', 'EigenLayer LRT', 'ethereum-mainnet', 'paused', 15,
   'High-capital. Phase 2 only.'),
  ('layerzero', 'LayerZero / Stargate', 'multi', 'paused', 10,
   'Multi-chain bridge points.')
on conflict (id) do update
set display_name = excluded.display_name,
    chain = excluded.chain,
    status = excluded.status,
    weight = excluded.weight,
    notes = excluded.notes;
